# The URL the site will be built for
base_url = "https://nexveridian.com"

# The site title and description; used in feeds by default.
title = ""
description = ""

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [{ name = "tags" }]

[markdown.highlighting]
theme = "one-dark-pro"

[extra]
# Put all your custom variables here
author = "NexVeridian"

# The logo text - defaults to 2 non-breaking spaces.
logo_text = "NexVeridian"

menu_items = [
    # set newtab to true to make the link open in new tab

    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    { name = "Home", url = "$BASE_URL" },

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    { name = "Blog", url = "$BASE_URL/archive" },
    { name = "Tags", url = "$BASE_URL/tags" },
    { name = "About Me", url = "$BASE_URL/about" },

    { name = "Resume", url = "$BASE_URL/Elijah_McMorris_Resume.pdf", newtab = true },
    { name = "Git.Nexv.dev", url = "https://git.nexveridian.com/NexVeridian", newtab = true },
]

show_only_description = true

# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "green"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "dark"

# Whether to show links to earlier and later posts
# on each post page.
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false
